# Generated by Django 2.0.3 on 2018-03-30 11:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionEvento',
            fields=[
                ('idClasificacion_evento', models.AutoField(primary_key=True, serialize=False)),
                ('Clasificacion_evento', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_cliente', models.CharField(max_length=45)),
                ('Apellido_cliente', models.CharField(max_length=45)),
                ('Telefono_cliente', models.CharField(max_length=45)),
                ('Correo_electronico', models.CharField(max_length=45)),
                ('Otros_datos_cliente', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEvento',
            fields=[
                ('idDetalle_evento', models.AutoField(primary_key=True, serialize=False)),
                ('FechaInicio', models.DateField(default=django.utils.timezone.now)),
                ('FechaFin', models.DateField()),
                ('ClasificacionEvento_idClasificacionEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda_eventos.ClasificacionEvento')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idEvento', models.AutoField(primary_key=True, serialize=False)),
                ('NombreEvento', models.CharField(max_length=45)),
                ('CodigoEvento', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='EventoCliente',
            fields=[
                ('idEventoCliente', models.AutoField(primary_key=True, serialize=False)),
                ('ClienteIdCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda_eventos.Cliente')),
                ('EventoIdEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda_eventos.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='EventoMaterial',
            fields=[
                ('idEventoMaterial', models.AutoField(primary_key=True, serialize=False)),
                ('EventoIdEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda_eventos.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('idMaterial', models.AutoField(primary_key=True, serialize=False)),
                ('CodigoMaterial', models.CharField(max_length=45)),
                ('nombreMaterial', models.CharField(max_length=45)),
                ('CantidadIdeal', models.IntegerField()),
                ('CantidadInicial', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='eventomaterial',
            name='MaterialIdMaterial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda_eventos.Material'),
        ),
        migrations.AddField(
            model_name='detalleevento',
            name='Evento_idEvento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda_eventos.Evento'),
        ),
    ]
